# https://starship.rs/config/#prompt

# Don't print a new line at the start of the prompt
add_newline = false

# Set prompt character
[character]
symbol = "➜ "

[directory]
truncation_length = 3
truncate_to_repo = false
